function plotPlume(model, states, resStats)
%%--------------------------------------------------------------------------
% PLOTPLUME Visualize CO2 plume thickness map and inventory growth
%
% Inputs:
%   model    - Upscaled Hybrid-VE model
%   states   - Cell array of simulation states
%   resStats - Structure generated by postProcess()
%%--------------------------------------------------------------------------

    G  = model.G;
    st = states{end};

    figure('Name', 'Johansen CO2 Plume & Inventory Diagnostics', ...
           'Color', 'w', ...
           'Position', [250, 250, 1200, 500]);

    %% ---------------------------------------------------------------------
    % Subplot 1: Free CO2 Plume Height Map
    %% ---------------------------------------------------------------------
    subplot(1, 2, 1);
    if isfield(st, 'h')
        hPlume = st.h;
    else
        hPlume = zeros(G.cells.num, 1);
    end

    plotCellData(G, hPlume, 'EdgeColor', 'none');
    colormap(hot);
    colorbar;
    title('Free CO_2 Plume Thickness h(t_{end}) [m]', 'FontSize', 12, 'FontWeight', 'bold');
    xlabel('X [m]'); ylabel('Y [m]');
    shading interp;
    axis equal tight;
    view(2);

    %% ---------------------------------------------------------------------
    % Subplot 2: Cumulative Injected CO2 Mass Trajectory
    %% ---------------------------------------------------------------------
    subplot(1, 2, 2);
    plot(resStats.tYears, resStats.co2MassMt, '-g', 'LineWidth', 2.5);
    grid on;
    xlabel('Time [Years]', 'FontSize', 11);
    ylabel('Total Stored CO_2 Mass [Mt]', 'FontSize', 11);
    title('Cumulative Stored CO_2 Mass Inventory', 'FontSize', 12, 'FontWeight', 'bold');

end
