function plotWellPerformance(resStats)
%%--------------------------------------------------------------------------
% PLOTWELLPERFORMANCE Plot well bottom-hole pressure and injection rates over time
%
% Inputs:
%   resStats - Structure generated by postProcess()
%%--------------------------------------------------------------------------

    if ~isfield(resStats, 'wellBHP') || isempty(resStats.wellBHP)
        disp('No well performance data available to plot.');
        return;
    end

    tYears    = resStats.tYears(2:end);
    wellNames = resStats.wellNames;
    nW        = numel(wellNames);

    figure('Name', 'Johansen Well Performance Profiles', ...
           'Color', 'w', ...
           'Position', [300, 300, 1200, 500]);

    %% ---------------------------------------------------------------------
    % Subplot 1: Injection Rates vs Time
    %% ---------------------------------------------------------------------
    subplot(1, 2, 1);
    hold on;
    for w = 1:nW
        plot(tYears, resStats.wellRate(:, w), 'LineWidth', 2, ...
            'DisplayName', char(wellNames{w}));
    end
    grid on;
    xlabel('Time [Years]', 'FontSize', 11);
    ylabel('Injection Rate [Mt/year]', 'FontSize', 11);
    title('Well Injection Rates Over Time', 'FontSize', 12, 'FontWeight', 'bold');
    legend('Location', 'best');

    %% ---------------------------------------------------------------------
    % Subplot 2: Bottom-Hole Pressure (BHP) vs Time
    %% ---------------------------------------------------------------------
    subplot(1, 2, 2);
    hold on;
    for w = 1:nW
        plot(tYears, resStats.wellBHP(:, w), 'LineWidth', 2, ...
            'DisplayName', char(wellNames{w}));
    end
    grid on;
    xlabel('Time [Years]', 'FontSize', 11);
    ylabel('BHP [bar]', 'FontSize', 11);
    title('Well Bottom-Hole Pressure (BHP)', 'FontSize', 12, 'FontWeight', 'bold');
    legend('Location', 'best');

end
