function plotPressure(model, states, resStats)
%%--------------------------------------------------------------------------
% PLOTPRESSURE Visualize spatial pressure buildup and average/peak trajectory
%
% Inputs:
%   model    - Upscaled Hybrid-VE model
%   states   - Cell array of simulation states
%   resStats - Structure generated by postProcess()
%%--------------------------------------------------------------------------

    G = model.G;

    figure('Name', 'Johansen Reservoir Pressure Diagnostics', ...
           'Color', 'w', ...
           'Position', [150, 150, 1200, 500]);

    %% ---------------------------------------------------------------------
    % Subplot 1: Spatial Pressure Buildup Map (Delta P at Final Time)
    %% ---------------------------------------------------------------------
    subplot(1, 2, 1);
    deltaP_final = resStats.finalDeltaP;
    
    plotCellData(G, deltaP_final, 'EdgeColor', 'none');
    colorbar;
    title('Pressure Buildup \DeltaP = P(t_{end}) - P(t_0) [bar]', 'FontSize', 12, 'FontWeight', 'bold');
    xlabel('X [m]'); ylabel('Y [m]');
    shading interp;
    axis equal tight;
    view(2);

    %% ---------------------------------------------------------------------
    % Subplot 2: Pressure Trajectory over Time
    %% ---------------------------------------------------------------------
    subplot(1, 2, 2);
    plot(resStats.tYears, resStats.pMax, '-r', 'LineWidth', 2, 'DisplayName', 'Max Field Pressure');
    hold on;
    plot(resStats.tYears, resStats.pAvg, '--b', 'LineWidth', 2, 'DisplayName', 'Average Pressure');
    grid on;
    xlabel('Time [Years]', 'FontSize', 11);
    ylabel('Pressure [bar]', 'FontSize', 11);
    title('Reservoir Pressure Evolution Over Time', 'FontSize', 12, 'FontWeight', 'bold');
    legend('Location', 'best');

end
