function plotEconomics(econResults)
%%--------------------------------------------------------------------------
% PLOTECONOMICS Plot project cash flow, NPV trajectory, and financial summary
%
% Inputs:
%   econResults - Structure generated by evaluateEconomics()
%%--------------------------------------------------------------------------

    tYears = econResults.tYears;
    netCF  = econResults.netCashFlowUSD / 1e6; % Million USD
    cumNPV = econResults.cumNpvUSD / 1e6;      % Million USD

    figure('Name', 'Johansen CO2 Storage Economic Evaluation', ...
           'Color', 'w', ...
           'Position', [200, 200, 1200, 500]);

    %% ---------------------------------------------------------------------
    % Subplot 1: Annual Cash Flow & Cumulative NPV Trajectory
    %% ---------------------------------------------------------------------
    subplot(1, 2, 1);
    yyaxis left;
    bar(tYears, netCF, 'FaceColor', [0.3 0.6 0.9], 'EdgeColor', 'none');
    ylabel('Net Cash Flow [Million USD]', 'FontSize', 11);

    yyaxis right;
    plot(tYears, cumNPV, '-r', 'LineWidth', 2.5);
    ylabel('Cumulative NPV [Million USD]', 'FontSize', 11);

    grid on;
    xlabel('Time [Years]', 'FontSize', 11);
    title('Project Financial Cash Flow & NPV Trajectory', 'FontSize', 12, 'FontWeight', 'bold');

    %% ---------------------------------------------------------------------
    % Subplot 2: Financial Summary Metrics Card
    %% ---------------------------------------------------------------------
    subplot(1, 2, 2);
    axis off;
    
    txtHeader = sprintf('\\bf\\fontsize{14}CO_2 Storage Economic Summary Card');
    txtBody = sprintf([ ...
        '\\fontsize{11}\n\n' ...
        '\\bfTotal Injected Mass:\\rm %.2f Mt\n\n' ...
        '\\bfInitial CAPEX:\\rm $%.2f Million USD\n\n' ...
        '\\bfProject NPV (r = 8%%):\\rm $%.2f Million USD\n\n' ...
        '\\bfLevelized Cost of Storage (LCOS):\\rm $%.2f / tonne\n\n' ...
        '\\bfCarbon Value Credit:\\rm $%.2f / tonne\n\n' ...
        '\\bfNet Economic Margin:\\rm $%.2f / tonne'], ...
        sum(econResults.annualInjMt), ...
        econResults.totalCapexUSD / 1e6, ...
        econResults.npvUSD / 1e6, ...
        econResults.lcosUSD, ...
        econResults.econCfg.carbonValueUSD, ...
        econResults.econCfg.carbonValueUSD - econResults.lcosUSD);

    text(0.1, 0.5, [txtHeader txtBody], 'Interpreter', 'tex');

end
