function econResults = evaluateEconomics(resStats, W, econCfg)
%%--------------------------------------------------------------------------
% EVALUATEECONOMICS Calculate project cash flows, NPV, LCOS, and payback
%
% Inputs:
%   resStats - Structure generated by postProcess()
%   W        - Well structure array
%   econCfg  - (Optional) Economic configuration from economicConfig()
%
% Outputs:
%   econResults - Structure containing full economic financial evaluation
%%--------------------------------------------------------------------------

    if nargin < 3 || isempty(econCfg)
        econCfg = economicConfig();
    end

    fprintf('\n=====================================\n');
    fprintf('Running Project Economic Assessment\n');
    fprintf('=====================================\n');

    tYears = resStats.tYears;
    nYears = numel(tYears);

    %% ---------------------------------------------------------------------
    % 1. Determine Injected CO2 Mass per Year
    %% ---------------------------------------------------------------------
    massTotalMt = resStats.co2MassMt;
    annualInjMt = [0; diff(massTotalMt)]; % Annual injected Megatonnes
    annualInjTonnes = annualInjMt * 1e6;   % Tonnes

    %% ---------------------------------------------------------------------
    % 2. Calculate CAPEX
    %% ---------------------------------------------------------------------
    nW = numel(W);
    totalWellCapex = nW * econCfg.wellCapexUSD;
    totalCapex     = econCfg.fixedCapexUSD + totalWellCapex;

    capexSchedule  = zeros(nYears, 1);
    capexSchedule(1) = totalCapex; % Lumped initial CAPEX at t = 0

    %% ---------------------------------------------------------------------
    % 3. Calculate Annual OPEX and Revenue
    %% ---------------------------------------------------------------------
    annualOpexUSD    = annualInjTonnes * econCfg.opexPerTonneUSD;
    annualRevenueUSD = annualInjTonnes * econCfg.carbonValueUSD;

    %% ---------------------------------------------------------------------
    % 4. Net Cash Flow & Discounted Cash Flow (DCF)
    %% ---------------------------------------------------------------------
    netCashFlowUSD = annualRevenueUSD - annualOpexUSD - capexSchedule;

    r = econCfg.discountRate;
    discountFactor = (1 + r) .^ (-tYears);
    dcfUSD         = netCashFlowUSD .* discountFactor;

    npvUSD         = sum(dcfUSD);
    cumNpvUSD      = cumsum(dcfUSD);

    %% ---------------------------------------------------------------------
    % 5. Levelized Cost of Storage (LCOS in $/tonne)
    %% ---------------------------------------------------------------------
    pvCosts = sum((capexSchedule + annualOpexUSD) .* discountFactor);
    pvMass  = sum(annualInjTonnes .* discountFactor);

    if pvMass > 0
        lcosUSDPerTonne = pvCosts / pvMass;
    else
        lcosUSDPerTonne = 0;
    end

    %% ---------------------------------------------------------------------
    % Store Results
    %% ---------------------------------------------------------------------
    econResults.tYears          = tYears;
    econResults.annualInjMt     = annualInjMt;
    econResults.totalCapexUSD   = totalCapex;
    econResults.annualOpexUSD   = annualOpexUSD;
    econResults.annualRevenueUSD= annualRevenueUSD;
    econResults.netCashFlowUSD  = netCashFlowUSD;
    econResults.dcfUSD          = dcfUSD;
    econResults.cumNpvUSD       = cumNpvUSD;
    econResults.npvUSD          = npvUSD;
    econResults.lcosUSD         = lcosUSDPerTonne;
    econResults.econCfg         = econCfg;

    fprintf('Economic Assessment Summary:\n');
    fprintf('  Total Stored Mass   : %.2f Mt\n', massTotalMt(end));
    fprintf('  Total CAPEX         : $%.2f Million USD\n', totalCapex / 1e6);
    fprintf('  Project NPV (8%% r)  : $%.2f Million USD\n', npvUSD / 1e6);
    fprintf('  Levelized Cost (LCOS): $%.2f / tonne CO2\n', lcosUSDPerTonne);
    fprintf('=====================================\n');

end
